// components/Expenditure/BasicDetailsSection.jsx
import InputField from "../Forms/InputField";
import SelectField from "../Forms/SelectField";
import DateField from "../Forms/DateField";
import { getFinancialYears } from "../../hooks/useFinancialYear";
import { useState } from "react";

const financialYearOptions = getFinancialYears(2023).map((fy) => ({
  label: fy,
  value: fy,
}));

const monthOptions = [
  { label: "Select Month", value: "" },
  { label: "January", value: "01" },
  { label: "February", value: "02" },
  { label: "March", value: "03" },
  { label: "April", value: "04" },
  { label: "May", value: "05" },
  { label: "June", value: "06" },
  { label: "July", value: "07" },
  { label: "August", value: "08" },
  { label: "September", value: "09" },
  { label: "October", value: "10" },
  { label: "November", value: "11" },
  { label: "December", value: "12" },
];

const BasicDetailsSection = ({
  register,
  control,
  departments,
  ddos,
  grants,
  isExpenditureLoading,
  watch,
  setValue,
  isEditMode,
}) => {
  const financialYear = watch("financialYear");
  const selectedMonth = watch("month");
  const [dateError, setDateError] = useState("");

  let minDate = "";
  let maxDate = "";
  let expectedYear = "";
  let expectedMonthName = "";

  if (financialYear && selectedMonth) {
    const [startYear, endYear] = financialYear.split("-");

    const year =
      Number(selectedMonth) >= 1 && Number(selectedMonth) <= 3
        ? endYear
        : startYear;

    expectedYear = year;
    expectedMonthName =
      monthOptions.find((m) => m.value === selectedMonth)?.label || "";

    const lastDay = new Date(year, selectedMonth, 0).getDate();

    minDate = `${year}-${selectedMonth}-01`;
    maxDate = `${year}-${selectedMonth}-${lastDay}`;
  }

  //  Validate typed date against allowed range
  const handleDateChange = (e) => {
    const typed = e.target.value; // "YYYY-MM-DD"
    if (!typed) {
      setDateError("");
      return;
    }

    if (!minDate || !maxDate) {
      setDateError("Please select a Financial Year and Month first.");
      setValue("voucherDate", "");
      return;
    }

    const typedDate = new Date(typed);
    const min = new Date(minDate);
    const max = new Date(maxDate);

    if (typedDate < min || typedDate > max) {
      setDateError(
        `Invalid date. Please enter a date within ${expectedMonthName} ${expectedYear} (${minDate} to ${maxDate}).`,
      );
      setValue("voucherDate", ""); // clear the invalid value
    } else {
      setDateError(""); // valid
    }
  };

  return (
    <>
      <SelectField
        label="Select Sector"
        name="sector"
        control={control}
        options={[
          { label: "Select Sector", value: "" },
          { label: "01-COUNCIL", value: "COUNCIL" },
          { label: "02-STATE", value: "STATE" },
        ]}
      />

      {isEditMode ? (
        <InputField
          label="Voucher No"
          name="voucherNo"
          register={register}
          readonly
          helperText="( System assigned )"
        />
      ) : (
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Voucher No
          </label>
          <input
            className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-100 
                       text-gray-500 cursor-not-allowed text-sm"
            value="Will be assigned on submit"
            disabled
            readOnly
          />
          <p className="text-xs text-gray-400 mt-1">
            ( Auto generated by system )
          </p>
        </div>
      )}

      <SelectField
        label="Financial Year"
        name="financialYear"
        control={control}
        options={[
          { label: "Select Financial Year", value: "" },
          ...financialYearOptions,
        ]}
      />

      <SelectField
        label="Month"
        name="month"
        control={control}
        options={monthOptions}
      />

      {/* ✅ Wrap DateField to intercept onChange */}
      <div>
        <DateField
          label="Date"
          name="voucherDate"
          register={register}
          min={minDate}
          max={maxDate}
          onChange={handleDateChange} // pass to DateField if it forwards ...rest to <input>
          // OR use the approach below if DateField doesn't forward onChange
        />
        {dateError && (
          <p
            style={{
              color: "red",
              fontSize: "12px",
              marginTop: "4px",
            }}>
            ⚠️ {dateError}
          </p>
        )}
      </div>

      <InputField
        label="Requisition No"
        name="requisitionNo"
        register={register}
      />

      <DateField
        label="Requisition Date"
        name="requisitionDate"
        register={register}
      />

      <SelectField
        label="Grant Name & No"
        name="grantNo"
        control={control}
        options={[{ label: "Select Grant", value: "" }, ...grants]}
      />

      <SelectField
        label="Department Name & Code"
        name="department"
        control={control}
        options={[{ label: "Select Department", value: "" }, ...departments]}
      />

      <SelectField
        label="Select DDO"
        name="ddo"
        control={control}
        options={[{ label: "Select DDO", value: "" }, ...ddos]}
      />
    </>
  );
};

export default BasicDetailsSection;
