ALTER TABLE "User" ADD COLUMN "canViewAllEntries" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "canEditAllEntries" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "canDeleteAllEntries" BOOLEAN NOT NULL DEFAULT false;